# -*- coding: utf-8 -*-
"""NLP_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1atQHO04O3maneDUeAFN3R8FZj4Mxl07z
"""

!pip install transformers torch pandas tqdm


from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import torch
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from tqdm import tqdm
import glob


INPUT_CSV = '/content/drive/MyDrive/FYP_Data/unprocessed_news.csv'
CHECKPOINT_DIR = '/content/drive/MyDrive/FYP_Data/checkpoints/'
FINAL_OUTPUT_CSV = '/content/drive/MyDrive/FYP_Data/finbert_scored_news.csv'
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

BATCH_SIZE = 32

def load_data():
    checkpoints = glob.glob(f"{CHECKPOINT_DIR}/*.csv")
    df = pd.read_csv(INPUT_CSV)

    if checkpoints:
        print(f"found {len(checkpoints)} checkpoints. resuming progress...")
        processed_ids = []
        for cp in checkpoints:
            cp_df = pd.read_csv(cp)
            processed_ids.extend(cp_df['id'].tolist())

        df = df[~df['id'].isin(processed_ids)]
        print(f"remaining rows to process: {len(df)}")

    return df

def run_finbert():
    df = load_data()
    if df.empty:
        print("all data has been processed, compiling final dataset")
        compile_final_dataset()
        return

    print("loading prosusai/finbert model onto GPU...")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"using device: {device}")

    tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
    model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert").to(device)

    results = []
    total_batches = (len(df) // BATCH_SIZE) + 1

    for i in tqdm(range(0, len(df), BATCH_SIZE), total=total_batches, desc="Scoring Headlines"):
        batch = df.iloc[i:i+BATCH_SIZE]
        headlines = batch['headline'].fillna("").tolist()

        # truncate to 512 tokens to prevent memory overflow errors
        inputs = tokenizer(headlines, padding=True, truncation=True, max_length=512, return_tensors="pt").to(device)

        with torch.no_grad():
            outputs = model(**inputs)
            # convert raw logits into clean 0-1 probabilities using softmax
            probabilities = F.softmax(outputs.logits, dim=-1).cpu().numpy()

        for idx, row in enumerate(batch.itertuples()):
            pos, neg, neu = probabilities[idx]

            results.append({
                'id': row.id,
                'sentiment_pos': pos,
                'sentiment_neg': neg,
                'sentiment_neu': neu
            })

        if len(results) >= 1000:
            cp_df = pd.DataFrame(results)
            cp_path = f"{CHECKPOINT_DIR}/checkpoint_{results[-1]['id']}.csv"
            cp_df.to_csv(cp_path, index=False)
            results = []

    if results:
        cp_df = pd.DataFrame(results)
        cp_path = f"{CHECKPOINT_DIR}/checkpoint_final.csv"
        cp_df.to_csv(cp_path, index=False)

    compile_final_dataset()

def compile_final_dataset():
    print("merging checkpoints into final output file...")
    all_cps = glob.glob(f"{CHECKPOINT_DIR}/*.csv")
    if not all_cps:
        print("no checkpoints found to merge")
        return

    final_df = pd.concat([pd.read_csv(f) for f in all_cps])
    final_df.to_csv(FINAL_OUTPUT_CSV, index=False)
    print(f"SUCCESS: saved fully scored dataset to {FINAL_OUTPUT_CSV}")

if __name__ == '__main__':
    run_finbert()