# -*- coding: utf-8 -*-
"""v4_LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hs-rQlp90oyg4yxbyvUBqThoQ0N2CMOu
"""

import os
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Input, LSTM, GRU, Dense, Dropout, Concatenate, BatchNormalization, Layer, Attention
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam
import tensorflow.keras.backend as K
from sklearn.model_selection import TimeSeriesSplit
from sklearn.preprocessing import StandardScaler

# --- PATHS ---
DATA_DIR = '/content/drive/MyDrive/FYP_Data'
MODEL_DIR = f'{DATA_DIR}/models'
os.makedirs(MODEL_DIR, exist_ok=True)

# --- METRICS & CUSTOM LAYERS ---
@tf.keras.utils.register_keras_serializable()
def directional_accuracy(y_true, y_pred):
    y_true_sign = tf.sign(y_true)
    y_pred_sign = tf.sign(y_pred)
    correct = tf.cast(tf.equal(y_true_sign, y_pred_sign), tf.float32)
    return tf.reduce_mean(correct) * 100

@tf.keras.utils.register_keras_serializable()
class TemporalAttention(Layer):
    def __init__(self, **kwargs):
        super(TemporalAttention, self).__init__(**kwargs)

    def build(self, input_shape):
        self.W = self.add_weight(name='attention_weight', shape=(input_shape[-1], 1),
                                 initializer='random_normal', trainable=True)
        self.b = self.add_weight(name='attention_bias', shape=(input_shape[1], 1),
                                 initializer='zeros', trainable=True)
        super(TemporalAttention, self).build(input_shape)

    def call(self, x):
        e = K.tanh(tf.matmul(x, self.W) + self.b)
        a = K.softmax(e, axis=1)
        output = x * a
        return K.sum(output, axis=1)

    def get_config(self):
        config = super(TemporalAttention, self).get_config()
        return config

# --- DATA LOADER ---
def load_tensors():
    print("Loading V4 RAW Tensors...")
    X_price = np.load(f'{DATA_DIR}/v4_X_price.npy')
    X_sentiment = np.load(f'{DATA_DIR}/v4_X_sentiment.npy')
    y_target = np.load(f'{DATA_DIR}/v4_y_target.npy')
    meta_data = np.load(f'{DATA_DIR}/v4_meta_data.npy', allow_pickle=True)
    return X_price, X_sentiment, y_target, meta_data

# --- V4 ARCHITECTURE (CROSS-ATTENTION) ---
def build_v4_model(price_shape, sentiment_shape):

    # Stream 1
    price_input = Input(shape=price_shape, name='price_input')
    price_seq = LSTM(64, return_sequences=True)(price_input)
    price_seq = Dropout(0.3)(price_seq)
    price_seq = BatchNormalization()(price_seq)

    # Stream 2
    sentiment_input = Input(shape=sentiment_shape, name='sentiment_input')
    sent_seq = GRU(64, return_sequences=True)(sentiment_input) # Changed from 32 to 64
    sent_seq = Dropout(0.3)(sent_seq)
    sent_seq = BatchNormalization()(sent_seq)


    attended_sentiment = Attention()([price_seq, sent_seq])

    # pool from 60 days to a single vector
    pooled_price = TemporalAttention(name='price_temporal_attention')(price_seq)
    pooled_sentiment = TemporalAttention(name='sentiment_temporal_attention')(attended_sentiment)

    # Fusion
    merged = Concatenate()([pooled_price, pooled_sentiment])
    z = Dense(32, activation='relu')(merged)
    z = Dropout(0.3)(z)

    output = Dense(1, activation='linear', name='target_return')(z)

    model = Model(inputs=[price_input, sentiment_input], outputs=output)

    model.compile(optimizer=Adam(learning_rate=0.001, clipnorm=1.0),
                  loss=tf.keras.losses.Huber(),
                  metrics=['mae', directional_accuracy])
    return model

# --- TRAINING LOOP ---
def train_v4_network():
    X_price, X_sentiment, y_target, meta_data = load_tensors()
    tscv = TimeSeriesSplit(n_splits=5)

    fold = 1
    yearly_results = []

    print("\n" + "="*60)
    print(" INITIATING V4 CHAMPION: CROSS-ATTENTION ENGINE")
    print(" FinBERT NLP Stream: GATED BY VOLATILITY | Target: T+5 Swing")
    print("="*60)

    for train_idx, val_idx in tscv.split(X_price):
        tf.keras.backend.clear_session()

        X_price_train, X_price_val = X_price[train_idx], X_price[val_idx]
        X_sent_train, X_sent_val = X_sentiment[train_idx], X_sentiment[val_idx]
        y_train, y_val = y_target[train_idx], y_target[val_idx]
        meta_val = meta_data[val_idx]

        val_dates = pd.to_datetime(meta_val[:, 1])
        start_date = val_dates.min().strftime('%Y-%m')
        end_date = val_dates.max().strftime('%Y-%m')

        print(f"\n[ V4 Fold {fold}/5 | Test Period: {start_date} to {end_date} ]")

        # Dynamic Scaling
        scaler = StandardScaler()
        samples_train, lookback, features = X_price_train.shape
        X_price_train_flat = X_price_train.reshape(-1, features)
        X_price_train_scaled = scaler.fit_transform(X_price_train_flat)
        X_price_train = X_price_train_scaled.reshape(samples_train, lookback, features)

        samples_val = X_price_val.shape[0]
        X_price_val_flat = X_price_val.reshape(-1, features)
        X_price_val_scaled = scaler.transform(X_price_val_flat)
        X_price_val = X_price_val_scaled.reshape(samples_val, lookback, features)

        model = build_v4_model(
            price_shape=(X_price.shape[1], X_price.shape[2]),
            sentiment_shape=(X_sentiment.shape[1], X_sentiment.shape[2])
        )

        callbacks = [
            EarlyStopping(monitor='val_loss', patience=6, restore_best_weights=True),
            ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-6, verbose=1)
        ]

        model.fit(
            x=[X_price_train, X_sent_train], y=y_train,
            validation_data=([X_price_val, X_sent_val], y_val),
            epochs=30, batch_size=64, callbacks=callbacks,
            shuffle=False, verbose=1
        )

        results = model.evaluate([X_price_val, X_sent_val], y_val, verbose=0)
        val_loss, val_mae, dir_acc = results[0], results[1], results[2]

        yearly_results.append({
            'fold': fold,
            'period': f"{start_date} to {end_date}",
            'accuracy': dir_acc
        })

        if fold == 5:
            model.save(f'{MODEL_DIR}/v4_champion_model.keras')

            pred_returns = model.predict([X_price_val, X_sent_val], verbose=0).flatten()
            pred_direction = (pred_returns > 0).astype(int)
            actual_direction = (y_val > 0).astype(int)

            results_df = pd.DataFrame({
                'Ticker': meta_val[:, 0],
                'Date': meta_val[:, 1],
                'Actual_5Day_Log_Return': y_val,
                'Predicted_5Day_Log_Return': pred_returns,
                'Actual_Direction': actual_direction,
                'Predicted_Direction': pred_direction,
                'Correct_Prediction': (actual_direction == pred_direction)
            })
            results_df.to_csv(f'{DATA_DIR}/v4_champion_predictions.csv', index=False)

        fold += 1

    print("\n" + "="*60)
    print(" FINAL V4 PERFORMANCE SUMMARY (CROSS-ATTENTION)")
    print("="*60)

    avg_acc = 0
    for res in yearly_results:
        print(f"Fold {res['fold']} | {res['period']}: {res['accuracy']:>5.2f}%")
        avg_acc += res['accuracy']

    avg_acc = avg_acc / len(yearly_results)

    print("-" * 60)
    print(f"OVERALL V4 AVERAGE: {avg_acc:.2f}%")
    print("=" * 60)

if __name__ == '__main__':
    train_v4_network()

from google.colab import drive
drive.mount('/content/drive')